<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Hospital2AdministrationSolutions" nsURI="platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore"
    nsPrefix="Hospital2AdministrationSolutions">
  <eClassifiers xsi:type="ecore:EClass" name="HospitalToAdministration" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaffToStaff" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatientToPatient" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomToShiftplan" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shiftplan"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoctorToStaff" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Doctor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NurseToStaff" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Nurse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_DepartmentRule" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Department"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_DoctorShiftplanRule" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__s1d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Doctor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__p1d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__p1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__s1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__pToP"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//PatientToPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__sToS"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//StaffToStaff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__s2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__sp" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shiftplan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__sh" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__p2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_DoctorToPatient" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Doctor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__p1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__ro" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__dep" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__pToP"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//PatientToPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__dToS"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//StaffToStaff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__p2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__t" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Treatment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_Hospital2AdministrationRule"
      eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__r" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Reception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORRESPONDENCE__htov"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//HospitalToAdministration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__v" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_NurseShiftplanRule" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__s1n" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Nurse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__ro" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__p1n" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__p1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__s1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__pToP"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//PatientToPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__sToS"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//StaffToStaff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__s2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__sp" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shiftplan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__sh" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__p2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_NurseToRoomRule" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__n" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Nurse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__r" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__dep" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__p1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__nToS"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//StaffToStaff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__pTop"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//PatientToPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__p2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__s" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_PatientInReception" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__hr" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__r" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Reception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__p1r" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__p1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__htovr"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//HospitalToAdministration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__htov"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//HospitalToAdministration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORRESPONDENCE__pTop"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//PatientToPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__vr" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__v" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__p2r" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__p2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_PatientInRoom" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__hp" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__ro" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__p1p" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__p1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__htovp"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//HospitalToAdministration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORRESPONDENCE__htov"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//HospitalToAdministration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORRESPONDENCE__pTop"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//PatientToPatient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__vp" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TARGET__v" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__p2p" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__p2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Patient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_RoomRule" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SOURCE__d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__ro" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_DocToStaffRule" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__s1d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Doctor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__s1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORRESPONDENCE__stot"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//StaffToStaff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORRESPONDENCE__htov"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//HospitalToAdministration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__s2d" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__s2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__v" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__sp" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shiftplan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__sh" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shift"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolNode_NurseToStaffRule" eSuperTypes="http://www.eMoflon.org/TGGRuntimeModel#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__s1n" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Nurse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__s1" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SOURCE__d" lowerBound="1"
        eType="ecore:EClass platform:/resource/HospitalExample/model/HospitalExample.ecore#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORRESPONDENCE__stot"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//StaffToStaff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORRESPONDENCE__htov"
        lowerBound="1" eType="ecore:EClass platform:/resource/Hospital2AdministrationSolutions/model/Hospital2AdministrationSolutions.ecore#//HospitalToAdministration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__s2n" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__s2" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Staff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__v" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Administration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__sp" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shiftplan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TARGET__sh" lowerBound="1"
        eType="ecore:EClass platform:/resource/AdministrationExample/model/AdministrationExample.ecore#//Shift"/>
  </eClassifiers>
</ecore:EPackage>
